Repository Sylius/SyliusGridBundle, pull requests merged in 2022-10, with the labels that each got.

#266 Change filter label type
  src/Bundle/Builder/Filter/Filter.php
  src/Bundle/Builder/Filter/FilterInterface.php
  src/Bundle/Tests/DependencyInjection/GridBuilderConfigurationTest.php
  src/Bundle/spec/Builder/Filter/FilterSpec.php
Labels: Bug

#264 feat: Allow to remove fields, filters and action from extended grid
  src/Bundle/Builder/GridBuilder.php
  src/Bundle/DependencyInjection/Configuration.php
  src/Bundle/Provider/ServiceGridProvider.php
  src/Bundle/Resources/config/services.xml
  src/Bundle/Tests/DependencyInjection/GridBuilderConfigurationTest.php
  src/Bundle/Tests/Provider/ServiceGridProviderTest.php
  src/Bundle/spec/Builder/GridBuilderSpec.php
  src/Bundle/spec/Provider/ServiceGridProviderSpec.php
  src/Bundle/test/src/Grid/BookGrid.php
  src/Bundle/test/src/Grid/BookmarkGrid.php
  src/Component/Configuration/GridConfigurationRemovalsHandler.php
  src/Component/Configuration/GridConfigurationRemovalsHandlerInterface.php
  src/Component/Provider/ArrayGridProvider.php
  src/Component/spec/Configuration/GridConfigurationRemovalsHandlerSpec.php
  src/Component/spec/Provider/ArrayGridProviderSpec.php
Labels: Feature

#269 Add support for deprecation contracts ^3.1
  composer.json
Labels: Maintenance

#271 Change to stable SyliusResourceBundle 1.10
  composer.json
Labels: Maintenance

#241 Adding conflicts with pagerfanta 2
  composer.json
Labels: Maintenance
