Repository Sylius/SyliusGridBundle, pull requests merged in 2022-01, with the labels that each got.

#197 Drop support for PHP7.4, Symfony version upgraded to 5.4
  .github/workflows/build.yml
  composer.json
  src/Component/composer.json
Labels: Maintenance

#200 Remove travis build status from README
  README.md
  src/Component/README.md
Labels: Maintenance

#191 [GridBuilder] Fix extending a grids as service
  UPGRADE.md
  src/Bundle/Provider/ServiceGridProvider.php
  src/Bundle/Resources/config/services.xml
  src/Bundle/Tests/DependencyInjection/GridBuilderConfigurationTest.php
  src/Bundle/Tests/Provider/ServiceGridProviderTest.php
  src/Bundle/spec/Provider/ServiceGridProviderSpec.php
  src/Bundle/test/src/Grid/BookmarkGrid.php
  src/Component/Configuration/GridConfigurationExtender.php
  src/Component/Configuration/GridConfigurationExtenderInterface.php
  src/Component/Provider/ArrayGridProvider.php
  src/Component/Tests/Dummy/FooFightersGrid.php
  src/Component/spec/Configuration/GridConfigurationExtenderSpec.php
  src/Component/spec/Provider/ArrayGridProviderSpec.php
Labels: Bug

#202 Fix grid builder method positions
  src/Bundle/Builder/GridBuilder.php
Labels: DX
