Repository Sylius/SyliusGridBundle, pull requests merged in 2022-02, with the labels that each got.

#208 Allow to run workflow manually
  .github/workflows/build.yml
Labels: Enhancement, DX

#209 Hotfix with datasources
  src/Bundle/Doctrine/DBAL/DataSource.php
  src/Bundle/Doctrine/ORM/DataSource.php
  src/Bundle/Doctrine/PHPCRODM/DataSource.php
  src/Bundle/spec/Doctrine/DBAL/DataSourceSpec.php
  src/Bundle/spec/Doctrine/ORM/DataSourceSpec.php
  src/Bundle/spec/Doctrine/PHPCRODM/DataSourceSpec.php
Labels: Bug

#216 [Docs] Add documentation for Grids as service
  docs/custom_action.md
  docs/custom_bulk_action.md
  docs/custom_field_type.md
  docs/custom_filter.md
  docs/field_types.md
  docs/filters.md
  docs/your_first_grid.md
Labels: Documentation
