Repository Sylius/SyliusGridBundle, pull requests merged in 2024-10, with the labels that each got.

#343 [Composer] Bump ResourceBundle to 1.12 beta
  composer.json
Labels: dependencies

#342 Add storage for filters
  src/Bundle/Resources/config/services/filters.xml
  src/Bundle/Storage/FilterStorageInterface.php
  src/Bundle/Storage/SessionFilterStorage.php
  src/Bundle/Tests/Integration/Storage/SessionFilterStorageTest.php
  src/Bundle/Tests/Unit/Storage/SessionFilterStorageTest.php
Labels: Feature

#344 [Composer] Bump sylius/resource-bundle dev dependency to last stable release
  composer.json
  tests/Application/config/bundles.php
Labels: Maintenance, dependencies
