Repository Sylius/SyliusGridBundle, pull requests merged in 2024-11, with the labels that each got.

#353 Update interface name in custom_filter docs
  docs/custom_filter.md
Labels: Documentation

#350 Update LICENSE year
  LICENSE
Labels: Maintenance

#351 Create LICENSE_OF_TRADEMARK_AND_LOGO
  LICENSE_OF_TRADEMARK_AND_LOGO
Labels: Maintenance

#345 Update RegisterFiltersPass.php
  src/Bundle/DependencyInjection/Compiler/RegisterFiltersPass.php
Labels: Bug

#355 Fix static analysis in RegisterFiltersPass
  src/Bundle/DependencyInjection/Compiler/RegisterFiltersPass.php
Labels: Bug
