Repository Sylius/SyliusGridBundle, pull requests merged in 2025-03, with the labels that each got.

#366 [CI] Add GitHub Action for creating upmerge PRs
  .github/workflows/upmerge_pr.yaml
Labels: Maintenance

#365 [FieldTypes] add vars option on DateTime & Twig field types
  src/Bundle/Tests/Functional/GridUiTest.php
  src/Bundle/Tests/Provider/ServiceGridProviderTest.php
  src/Bundle/spec/Builder/Field/DateTimeFieldSpec.php
  src/Bundle/spec/Builder/Field/StringFieldSpec.php
  src/Component/FieldTypes/DatetimeFieldType.php
  src/Component/FieldTypes/StringFieldType.php
  src/Component/spec/FieldTypes/DatetimeFieldTypeSpec.php
  tests/Application/config/sylius/grids.yaml
  tests/Application/config/sylius/grids/book.php
  tests/Application/src/Grid/BookGrid.php
  tests/Application/templates/crud/index.html.twig
Labels: Enhancement, DX

#367 fix grid sorting with sorting key not defined and refactor grid definition creation
  phpunit.xml.dist
  src/Bundle/Provider/ServiceGridProvider.php
  src/Bundle/Resources/config/services.xml
  src/Bundle/spec/Provider/ServiceGridProviderSpec.php
  src/Component/Configuration/GridConfigurationSortingHandler.php
  src/Component/Configuration/GridConfigurationSortingHandlerInterface.php
  src/Component/Provider/ArrayGridProvider.php
  src/Component/Tests/Unit/Configuration/GridConfigurationSortingHandlerTest.php
  src/Component/spec/Provider/ArrayGridProviderSpec.php
  tests/Application/config/sylius/grids.yaml
  tests/Application/config/sylius/grids/book.php
  tests/Application/src/Grid/BookGrid.php
Labels: Bug, Enhancement
